### ISSUE TITLE
Add layers to map

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#10]
Right now we can search for layers but there is nothing visible in the map

**Comment by jfarmer91** [comment]
Yep I am trying to figure this out. For some reason I couldn't get it to add the layers to map. This is the file I created for that linked it to the index.html but it wasn't working [mapLayers.js](https://files.zenhub.io/564f295ff38ae06058fda689)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jfarmer91** [comment]
Crossings, Signs, RailLines, and AADT are present. symbology isn't finished. Crossing and Sign feature services are not the final services the data will point to. Need to point these services to the corrected data at some point after going through the rest of bobs QC work
