### ISSUE TITLE
Search results - put World Geocoder on bottom?

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#11]
Right now if you type a DOT number it turns up some strange results from Esri's geocoder at the top. Can those go at the bottom?
![image](https://cloud.githubusercontent.com/assets/8357118/11301582/4ae069c0-8f66-11e5-96c9-d77b3cae1fcd.png)

**Comment by jfarmer91** [comment]
I would like to do that. I mentioned that in the milestone for the completed search box but hadn't created an issue yet

**Comment by jfarmer91** [comment]
Fixed in merge #21
