### ISSUE TITLE
Satellite image layer

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#131]
A transparent streets layer isn't the most effective way to visualize both street names and satellite. We can find a "reference" tile layer that we like to load on top of the satellite layer.

**Comment by jfarmer91** [comment]
Yeah not sure the streets have a reference tile layer. I think street names are usually within the basemap itself. Pretty sure the reference tile layers label counties, towns, stores, parks, etc

**Comment by jfarmer91** [comment]
Covered in Issue #162
