### ISSUE TITLE
Final checks - Beta 2

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#134]
Other:
- [x] Remove livereload.js
- [x] update Changelog.md
- [x] Update Readme.md
  Tests: 

---
## Usability:

Map page
- [x] Loads correctly
- [x] Loads in a reasonable time
- [x] Feature layers show up
- [x] Feature layers are clickable
- [x] Popups work
- [x] Popup content loads
- [x] Report link works
- [x] Help popup works
- [x] Dismiss help popup works

Widgets
- [x] Zoom in
- [x] Zoom out
- [x] Toggle AADT
- [x] Toggle Signs

Search Test - Main Page
- [x] Empty 
- [x] Gibberish
- [x] Street name
- [x] DOT # - dashes
- [x] RRXINGNUM
- [ ] DOT # - spaces

Report page:
- [x] Loads correctly
- [x] Loads in a reasonable time
- [x] Crossing data shows up
- [x] Crossing images show up

Search Test - Report Page
{None this release}

---
## Compatibility:

Mobile
- [ ] iPhone 5s
- [ ] iPhone 6s+
- [ ] Nexus 6P

Browsers
- [ ] IE 8
- [ ] IE 9
- [ ] IE 10
- [x] Firefox - FONT DIFFERENT
- [x] Chrome
- [x] Safari

Bandwidth:
Main page load:
- [x] Good 2G: 17.5s
- [x] Regular 3G: 11s
- [x] 4G: 2.75s
- [x] DSL: 4s
- [x] WiFi: 2s
- [x] Ethernet: 1.5s

Popup load:
- [ ] Good 2G: NA
- [x] Regular 3G: 5min
- [x] 4G: 1.9m
- [x] DSL: 3m
- [x] WiFi: 11s
- [x] Ethernet: 5.5s

Sizes
- [x] 480px 
- [x] 768px
- [x] 992px
- [x] 1200px

Accessibility
- [ ] colorblind safe NO - see #139

**Comment by jfarmer91** [comment]
- Help button doesn't work in IE10 or earlier
- placeholder text in search bar doesn't show up in IE9 or before.
- entire navbar is messed up in IE8 and earleir
