### ISSUE TITLE
Thumbnails instead of full images?

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#136]
I wonder if it's possible (it may not be) to serve up image thumbnails instead of the full images from the map service. Multi-minute load times on 2G connections

**Comment by jfarmer91** [comment]
Would have to create thumbnails server side in order for this to help load time at all. The only ways I have found to do it with javascript require loading of the full image before converting it to a thumbnail (not at all helpful for us). 

Partially solved loading issue by only loading photos in popup after a button is clicked. This way, loading is only affected if the user chooses to view photos. If they are just there for other info, popup loads immediately. 
- Closed by choice
