### ISSUE TITLE
Colorblind-safe crossing symbol colors

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#139]
Good and Fair are indistinguishable to a colorblind person

**Comment by TheMapSmith** [comment]
The colorblind-compliant scale used in VTransparency
![image](https://cloud.githubusercontent.com/assets/8357118/12126532/c0e6c5c4-b3bf-11e5-8c83-803dab68a312.png)

**Comment by jfarmer91** [comment]
This is just a png file. how do i get the rgb or hex codes from it?

**Comment by jfarmer91** [comment]
Map published from Z:\PPID\Rail\GIS\Engineering\Crossings\Inspection\2015_dev\Map\CrossingInspection2015.mxd

**Comment by jfarmer91** [comment]
Closed by commit 7afc953535c8686c5c247e0d5195c66141bd58ce
