### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#153]

**Comment by jfarmer91** [comment]
Maptiks?

**Comment by TheMapSmith** [comment]
- [x] Basic GA for pageviews 
- [x] Screen sizes
- [ ] Devices

Event tracking 
- [x] Help clicks
- [x] Full report clicks - count
- [x] Full report - DOT # capture
- [x] Image full loads
- [x] Search terms capture
- [ ] Search suggestions - click on result 
- [x] Press "Enter" after search
- [ ] Search suggestions scroll down results
- [x] Search error results
- [ ] Popup error messages
- [ ] Page performance (?)
- [x] Imagery toggle

Map analytics
- [x] Basic maptiks
- [ ] Advanced maptiks

**Comment by TheMapSmith** [comment]
- [x] Legend popup clicks

**Comment by jfarmer91** [comment]
## Capture
- [x] DOT_Num of crossing viewed 
- [x] Computer ID of user

**Comment by TheMapSmith** [comment]
added maptiks with 9343e808633fc048a00972862e282eec57b1f368
