### ISSUE TITLE
Map Symbology/Visibility

### ISSUE THREAD

**Issue by jfarmer91** [VTrans-Rail/crossing-inspection#16]
Need to fix layer symbology and map interactions so it is soup-er slick. 

Thinking:
- Only have rail lines and basemap visible at full extent
- aadt lines are only visible if turned on 
  - also need to change their symbology because it looks clunky when zoomed out
- Maybe change crossing symbology to something a little simpler

**Comment by TheMapSmith** [comment]
Can we also change the background map at zoom scales?
- [x] Low zoom = [Topographic](http://vtrans.maps.arcgis.com/home/item.html?id=6e03e8c26aad4b9c92a87c1063ddb0e3)
- [ ] High zoom = Imagery [http://vtrans.maps.arcgis.com/home/item.html?id=6e03e8c26aad4b9c92a87c1063ddb0e3](http://vtrans.maps.arcgis.com/home/item.html?id=6e03e8c26aad4b9c92a87c1063ddb0e3)

**Comment by TheMapSmith** [comment]
Push AADT symbology and high-zoom basemap trigger to later releases
