### ISSUE TITLE
Search Box needs to be resized and moved on mobile devices

### ISSUE THREAD

**Issue by jfarmer91** [VTrans-Rail/crossing-inspection#17]
The new styling for the search box looks strange with the white space for the header that the box is supposed to be inside. Need to figure out a way to fix this. 

![image](https://cloud.githubusercontent.com/assets/15361539/11307721/fef75600-8f87-11e5-9f5d-40d517cd12e5.png)

**Comment by TheMapSmith** [comment]
Thanks I didn't get enough time to test the changes. Feel free to revert that change (I think it's like top:75px)
