### ISSUE TITLE
Add link that will act as request for popup to create report

### ISSUE THREAD

**Issue by jfarmer91** [VTrans-Rail/crossing-inspection#25]

**Comment by TheMapSmith** [comment]
The popup should have a query string at the end of the URL like:
`http://vtrans-rail.github.io/crossing-inspection/report.html?dotnum=` with the DOT number attribute appended to the end. The report page will parse that query string and run the report when the page loads

**Comment by jfarmer91** [comment]
Closed in Pull Request #79
