### ISSUE TITLE
Develop tests

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#3]
Each commit should pass certain tests. Let's come up with a list of them

**Comment by TheMapSmith** [comment]
Let's brainstorm here in the comments
Mobile tests:
iOS:
- [ ] iPhone 5s
- [ ] iPad 1

Android:
- [ ] Nexus 6p
- [ ] Galaxy S4

https://www.google.com/webmasters/tools/mobile-friendly/

**Comment by jfarmer91** [comment]
Different IE Versions
_(stephen)_  
- [ ] IE 8
- [ ] IE 9  
- [ ] IE 10

**Comment by TheMapSmith** [comment]
Search test:
- [ ] Empty search
- [ ] Gibberish search
- [ ] Street name search
- [ ] DOT Number search (123-456X)
- [ ] Other DOT number searches: 
- [ ] 123456x
- [ ] 123 456 x

**Comment by TheMapSmith** [comment]
Modern browsers:
- [ ] Chrome 46
- [ ] Firefox 42
- [ ] Safari 9

**Comment by TheMapSmith** [comment]
Responsive sizes:
- [ ] Smartphone (320px)
- [ ] Phablet (480px)
- [ ] Tablet (768px)
- [ ] Desktop - sm (992px)
- [ ] Desktop - lg (1200px)

**Comment by TheMapSmith** [comment]
Accessibility 
(I don't know anything about this - will need to research)

**Comment by TheMapSmith** [comment]
Do the "search test" on the report page as well

**Comment by TheMapSmith** [comment]
closed by https://github.com/VTrans-Rail/crossing-inspection/commit/05f42acf46369735bb4372f845335b2fe25d4907
