### ISSUE TITLE
Styling - Main page

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#33]

**Comment by TheMapSmith** [comment]
@jfarmer91 Do you think anything else needs to be done here before b1?

**Comment by jfarmer91** [comment]
Not really. Probably want to change the symbology of map and maybe add a legend or labels at some point. But that can be a separate issue. One thing would be adding a semi-transparent layer that covers the map and has basic instructions for how to use the website. The layer would disappear if you touch any part of the screen. Could have the following text in the center:

Navigate to crossings through the Search Box or the Map

**Comment by TheMapSmith** [comment]
I like that idea but let's call this done as far as b1 is concerned. Map styling and page overlay could be two different issues for future development.

**Comment by jfarmer91** [comment]
Sounds good.
