### ISSUE TITLE
Basic report page styling

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#34]
- [x] Navbar setup
- [x] Add bootstrap
- [x] Make header responsive
- [x] Limit returned results
- [x] Add bootstrap formatting to result string
- [ ] Use alias instead field name

**Comment by TheMapSmith** [comment]
Actually I just realized that the map popup is the "short" results and the report page is the "full" results. We should probably include _most_ of the fields (but still not all)

**Comment by jfarmer91** [comment]
Yeah. That's why I put the asterisk there. Figured we would remove some fields later but probably want to style the page for most of the results, not just a handful.

**Comment by TheMapSmith** [comment]
Calling this good for now. Will open a new issue for report content formatting
