### ISSUE TITLE
Shorten search results

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#44]
Currently the search results look like this:

<img width="535" alt="screen shot 2015-11-30 at 1 26 27 pm" src="https://cloud.githubusercontent.com/assets/8357118/11480555/035a9e6a-9766-11e5-9e63-760c19e4c8ea.png">

I suggest the quick results look like:

**851-168S**: _Lake Paran Rd_ on the VTR B&R @ MP 3.05 _(Fair)_

**Comment by jfarmer91** [comment]
Closed in pull request #77
