### ISSUE TITLE
Add field metadata explanation on hover

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#69]
For all of the fields add a the metadata definition on hover (or mobile tap) so that users can get a quick explanation of a field if they're confused

**Comment by jfarmer91** [comment]
I like this a lot

**Comment by jfarmer91** [comment]
Commits below are related to this: 
- 6d3d97fe97037a5b4d158d4370e2f28a74f109d8
- fb0657656b77333e96401ad03c8e3507dcfee8a2
- 4e8ec8461eae4c6847c2217114d237b82c7a0686
