### ISSUE TITLE
Search button on mobile doesn't work

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#74]
Something about two buttons having the same ID?

**Comment by TheMapSmith** [comment]
Punting to b2 - will just hide the navbar content for b1 since the main functionality is to come from the popup window into the full report page

**Comment by TheMapSmith** [comment]
We still haven't re-enabled the search box on the report page so we don't need to have it done by b2

**Comment by jfarmer91** [comment]
Punting to final release. Might not even have a search on the report page

**Comment by jfarmer91** [comment]
Choosing not to have a search option on report page
