### ISSUE TITLE
Remove Full Report link from actionList on popups for signs and aadt.

### ISSUE THREAD

**Issue by jfarmer91** [VTrans-Rail/crossing-inspection#78]
We only have full reports for crossings. Right now 

```
var link = domConstruct.create("a", {
  "class": "action",
  "id": "fullReport",
  "innerHTML": "Full Report",
  "href": "javascript:void(0);"
}, dojo.query(".actionList", map.infoWindow.domNode)[0]);
```

adds the link to all map infoWindows which means all popups. Somehow need to figure out what to replace "map.infoWindow.domNode" with so it only shows up on crossing popup. Haven't figured it out yet.

**Comment by TheMapSmith** [comment]
Remove from AADT popup and leave it/enable it for signs popups

**Comment by jfarmer91** [comment]
- [x] Enable Full Report link for signs popup
- [ ] Remove Full Report link from AADT popup

**Comment by jfarmer91** [comment]
punting "Remove full Report Link from AADT popup" to Issue #135 
- full report link was enabled for sign popups in pull request #133
